config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'static_page/venue'
  get 'static_page/speakers'
  get 'static_page/pastevents'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'static_page#overview'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
          
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

def hello
	    render html: "hello world"
	end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def overview
  end
  def speakers
  end
  def venue
  end
  def pastevents
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/layouts/_calendar.html.erb
<html>
<head>

<!-- AddEvent script -->
<script type="text/javascript" src="https://addevent.com/libs/atc/1.6.1/atc.min.js" async defer></script>

</head>
<body>

<!-- Button code -->
<div title="Add to Calendar" class="addeventatc">
    Add to Calendar
    <span class="start">07/16/2020 11:00 AM</span>
    <span class="end">07/16/2020 12:00 PM</span>
    <span class="timezone">IST(India)
</span>
    <span class="title">Virtual meetup on AI transformation</span>
    <span class="description">Discussion on real world use cases of AI transformation</span>
    <span class="location">Online</span>
</div>

</body>
</html>

app/views/layouts/_footer.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
 <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">
 <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link rel="stylesheet" href="http://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css">   
 
  <style>
    

* { 
margin: 0;
}
.site-footer
{ 
height: 280px;
} 
.site-footer {
background: black; 
}
/*footerdata*/

.footer-left{
  padding-left: 100px;
  padding-top: 30px;
}



  

  </style>
</head>
<body>

  
<footer class="site-footer" class="row">
   
    <div class="footer-left" class="column" style="float: left; width: 40%;">
       <h3 > <b style="color: white;">About</b><span style="font-family: 'Dancing Script', cursive; color: yellow">&nbsp;TechMeets</span></h3>
        <p class="footer-links">
          <a href="#">Home</a>
          |
          <a href="#">Blog</a>
          |
          <a href="#">About</a>
          |
          <a href="#">Contact</a>
        </p>
        <p class="footer-company-name" style="color: white">© 2020 TechMeets </p>
    </div>
       
      </div> 
      <div class="footer-right" class="column" style="float: right; width: 40%;padding-top: 30px">
          <p class="footer-company-about" style="color: white;">
          <span style="color: white;"><b><font size="+2">About the company</font><b></span><br>
          We publicize events of different companies and allow interested candidates to register for the event.</p>
        <div class="footer-icons">
          <a href="#"><i class="fa fa-facebook fa-3x"></i></a>&nbsp;
          <a href="#"><i class="fa fa-twitter fa-3x"></i></a>&nbsp;
          <a href="#"><i class="fa fa-instagram fa-3x"></i></a>&nbsp;
          <a href="#"><i class="fa fa-linkedin fa-3x"></i></a>&nbsp;
          <a href="#"><i class="fa fa-youtube fa-3x"></i></a>&nbsp;
        </div>
        <div style="padding-left: 50px">
          <i class="fa fa-map-marker fa-3x"></i>
           <span style="color: white">Hyderabad,Telangana,
            
            500070</span>
        </div>
         <div style="padding-left: 50px">
          <i class="fa fa-envelope fa-3x"></i>
          <span style="color: white">support@techmeets.com</span>
        </div>
     </div>

   
</footer>




  
</body>
</html>

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Responsive Navbar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <link rel="icon" type="image/x-icon" href="../event.png">
    <style>
a:link {
  color: orange;
  background-color: transparent;
  text-decoration: orange;
}
a:visited {
  color: orange;
  background-color: transparent;
  text-decoration: none;
}
a:hover {
  color: red;
  background-color: transparent;
  text-decoration: underline;
}
a:active {
  color: orange;
  background-color: transparent;
  text-decoration: underline;
}
</style>
  </head>
  <body  style="margin:0 ;padding:0;">
    <nav >
      <input type="checkbox" id="check">
      <label for="check" class="checkbtn">
        <i class="fas fa-bars"></i>
      </label>
      <label class="logo" >𝓣𝓮𝓬𝓱𝓜𝓮𝓮𝓽𝓼</label>
      <ul>
        <li >
          
          <%= link_to "ᴏᴠᴇʀᴠɪᴇᴡ", root_path %><a href="/" ></a>
        </li>
        <li>
          <%= link_to "sᴘᴇᴀᴋᴇʀs", static_page_speakers_path %><a href="/"></a>
        </li>
        <li>
          <%= link_to "venue", static_page_venue_path %><a href="/"></a>
        </li>
        <li>
          <% if !user_signed_in?%>
          <p class="sign_in"><%= link_to "ʟᴏɢɪɴ", new_user_session_path %><a href="/"></a>
          <% end %>
           <% if user_signed_in?%>
             <%= link_to "ᴇᴠᴇɴᴛs", static_page_pastevents_path %>&nbsp;
              <%= link_to 'ᴇᴅɪᴛ ᴘʀᴏꜰɪʟᴇ', edit_user_registration_path %>&nbsp;
           <%= link_to('ʟᴏɢᴏᴜᴛ', destroy_user_session_path, :method => :delete) %><a href="/"></a>
           
           <% end %>

        </li>
        <li>
          <%= link_to "sɪɢɴᴜᴘ", new_user_registration_path %><a href="/"></a>

        </li>
         
       
        

</ul>
 
</nav>

    
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechMeets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <% flash.each do |message_type,message| %>

    <div class="alert alert-primary "role="alert">
          <%= message %> 
  
 </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>



  </body>
</html>

app/views/static_page/overview.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title></title>
 
 <style>
a:link {
  color: orange;
  background-color: transparent;
  text-decoration: orange;
}
a:visited {
  color: orange;
  background-color: transparent;
  text-decoration: none;
}
a:hover {
  color: red;
  background-color: transparent;
  text-decoration: underline;
}
a:active {
  color: orange;
  background-color: transparent;
  text-decoration: underline;
}
</style>
</head>
<body style="margin:0 ;padding:0">





	
<%= image_tag("company/back.jpg", :height=>728,:width=>1838, :crop=>"fill",:position=> "relative")%>


<br><br>
<center><button  class="button"><%= link_to "Register Now", new_user_registration_path,background:"none" %><a href="/"></a></button></center>
<p></p>
<center><%= render 'layouts/calendar' %></center>
<br>
<marquee direction="right" bgcolor="yellow" scrolldelay=1  height=25 vspace=2px><b>Welcome to H<sub>2</sub>o.ai virtual meet </b></marquee>
<!-- <marquee direction = "up">The direction of text will be from bottom to top.</marquee> -->

<div style="padding-left: 50px ;background-color: white">
<p style="text-align: center;"><font color="red" face="Verdana, Geneva, sans-serif" size="+10">A conference for creators like you:</font></p>
<br><br>
<h3><b>Details:</b></h3><br>
<p>
<font  size="+1" >
AI is unlocking new potential for every enterprise. Organizations are using AI and machine learning technology to inform business decisions, predict potential issues, and provide more efficient, customized customer experiences. We will walk through some real use cases we have been a part of across a variety of industries such as finance, retail, and healthcare as well as the impact AI brought to these businesses.
</p>
</font><br><br>
<font  size="+1" >
<b>A few of the companies use cases we will discuss are:</b><br>
<ul  style="list-style-type:disc;padding-left: 20px">
	<li>-AT&T</li>
	<li>-PWC</li>
	<li>-Bill.com</li>
	<li>-G5</li>
</ul></font><br><br>



<div class="row">
  <div class="column" style="float: left; width: 70%;">
  	<p>
	    <font  size="+1" >
H2O.ai is a visionary leader in AI and machine learning and is on a mission to democratize AI for everyone. We believe that every company can become an AI company, not just the AI Superpowers. We are empowering companies with our leading AI and Machine Learning platforms, our expertise, experience and training to embark on their own AI journey to become AI companies themselves. All companies in all industries can participate in this AI Transformation.<br><br>

Tune into this virtual meetup to learn how companies are transforming their business with the power of AI and where to start.
       </font>
    </p>
  </div>
  <div class="column" style="float: left; width: 29%; ">
  	<marquee direction="down" bgcolor="orange" >
        <font color="green">
  		<p style="text-align: center;">Thursday, July 16, 2020<br>
        11:00 AM to 12:00 PM GMT+5:30<br><br>

        Online event
        </p>
        </font>
  	</marquee>
  </div>
</div>
</div>

<br><br><br>
<div>
<center><svg width="7em" height="7em" viewBox="0 0 16 16" class="bi bi-mic" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M3.5 6.5A.5.5 0 0 1 4 7v1a4 4 0 0 0 8 0V7a.5.5 0 0 1 1 0v1a5 5 0 0 1-4.5 4.975V15h3a.5.5 0 0 1 0 1h-7a.5.5 0 0 1 0-1h3v-2.025A5 5 0 0 1 3 8V7a.5.5 0 0 1 .5-.5z"/>
  <path fill-rule="evenodd" d="M10 8V3a2 2 0 1 0-4 0v5a2 2 0 1 0 4 0zM8 0a3 3 0 0 0-3 3v5a3 3 0 0 0 6 0V3a3 3 0 0 0-3-3z"/>
</svg></center>  
<br>
<center><b><font size="+2">Our Speakers</font></b></center> 
<br>
<center>

	<p>
<font size="+1">
-<b>Parul Pandey</b>, Data Science Evangelist and Kaggle Grandmaster, H2O.ai<br>
-<b>Shivam Bansal</b>, Senior Data Scientist and Kaggle Grandmaster, H2O.ai
</font>
	</p>
</center>
</div>
<br><br>
<p style="padding-left: 50px"><font size="+3"><b>Attendees</b></font></p>
<div style="padding-left: 50px">
	<div class="row row-cols-1 row-cols-md-3">
  <div class="col mb-4">
    <div class="card">
      <img src="https://www.jpmorganchase.com/corporate/news/images/melinda-welsh-callout.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Swastika</h5>
        <p class="card-text">Member</p>
      </div>
    </div>
  </div>
  <div class="col mb-4" >
    <div class="card">
      <img src="https://www.southwalesargus.co.uk/resources/images/3420914.jpg?display=1&htype=90&type=responsive-gallery" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Salena</h5>
        <p class="card-text">Member</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card">
      <img src="https://media.gq-magazine.co.uk/photos/5d13a8c59fa601318a8399ed/master/w_1920,c_limit/bradley-cooper-hp-gq-5mar19_shutterstock_b.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Helen</h5>
        <p class="card-text">Member </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card">
      <img src="https://www.futureinstitute.in/wp-content/uploads/2017/01/Chandrashekar-Hariharan.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">chandra shekhar</h5>
        <p class="card-text">organizer</p>
      </div>
    </div>
  </div>
   <div class="col mb-4">
    <div class="card">
      <img src="https://www.goldmansachs.com/worldwide/india/multimedia/careers-meet-our-people-image.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Niharika</h5>
        <p class="card-text">co-organizer</p>
      </div>
    </div>
  </div>
   <div class="col mb-4">
    <div class="card">
      <img src="https://miro.medium.com/fit/c/336/336/1*xR3EuR3gK1KkVLrWT1TfEA.jpeg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">sai kiran</h5>
        <p class="card-text">promoter</p>
      </div>
    </div>
  </div>
</div>
</div>



 



</body>
</html>

app/views/static_page/pastevents.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
      .blink {
      animation: blinker 0.6s linear infinite;
      color: #1c87c9;
      font-size: 30px;
      font-weight: bold;
      font-family: sans-serif;
      }
      @keyframes blinker {  
      50% { opacity: 0; }
      }
      .blink1 {
      animation: blinker 0.6s linear infinite;
      color: brown;
      font-size: 30px;
      font-weight: bold;
      font-family: sans-serif;
      }
      @keyframes blinker {  
      50% { opacity: 0; }
      }
     
     
    </style>
</head>
<body>

<marquee direction="right" bgcolor="lightgreen" width=100% height=40px vspace=5px style="padding-top: 2px"><p class="blink">welcome to the world of AI and ML</p></marquee>
    <div style="padding-left: 50px;padding-top: 50px;">
    <h2>Past Events from H<sub>2</sub>o.io</h2>
    <p>click on the following links to watch an event</p>
    <a href="https://www.youtube.com/watch?v=ZqCoFp3-rGc">1.H2O Driverless AI Demo</a><br>
    <a href="https://www.youtube.com/watch?v=HvYWE6YFoR0">2.Intro to Driverless AI - Hands-on Training - #H2OWorld 2019 NYC</a><br>
    <a href="https://www.youtube.com/watch?v=8T0bK_gJTI8">3.Keynote by Sri Ambati - #H2OWorld 2019 NYC</a><br>
    <a href="https://www.youtube.com/watch?v=khjW1t0gtSA">4.Your AI Transformation - Virtual Meetup</a><br>
    <a href="https://www.youtube.com/watch?v=CY3t11vuuOM">5.Interpretable Machine Learning Using LIME Framework - Kasia Kulma (PhD), Data Scientist, Aviva</a><br>
    <a href="https://www.youtube.com/user/0xdata/videos"><b style="color: red">click here</b> complete collection of past events</a>
    </div>
    <div style="padding-top: 70px;padding-left: 50px">
    	<h2>Upcoming events </h2>
       	<a href="https://register.gotowebinar.com/register/1144058749346313488">Your AI Transformation Part 2: Real World Use Cases </a>
       	&nbsp;&nbsp;&nbsp;Thursday, July 16, 2020
11:00 AM to 12:00 PM GMT+5:30
<br>
<p class="blink1">For more events stay tuned!!</p>

    </div>
     
       </body>
</html>

app/views/static_page/speakers.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>

	<style>
		 body { background: #fff2e6; }

a:link {
  color: blue;
  background-color: transparent;
  text-decoration: orange;
}
a:visited {
  color: blue;
  background-color: transparent;
  text-decoration: none;
}
a:hover {
  color: blue;
  background-color: transparent;
  text-decoration: underline;
}
a:active {
  color: blue;
  background-color: transparent;
  text-decoration: underline;
}

	</style>
</head>
<body>
	
  <center style="padding-top: 50px"><i class="fa fa-microphone fa-5x" aria-hidden="true"></i></center>
	
	<div style="padding-left: 50px;padding-right: 50px" >
		<center><font size="+3" style="color: red">Your speakers Line-up</font> </center>
		<%= image_tag("company/2.png")%>
	<p style="padding-top: 50px"><font size="+2" color="black"><b>Parul Pandey</b></font>&nbsp;&nbsp;<br><br><font size="+1" color="black">follow on: &nbsp;&nbsp;<a href="https://in.linkedin.com/in/parulpandeyindia" style="background: none"><i class="fa fa-linkedin fa-3x" aria-hidden="true"></i></a></font>
		<br>
		<a href="https://sites.google.com/view/parul-pandey/home" style="background: none;text-decoration: none"><font color="indigo">www.parulpandey.com</font></a>
<br>
<br>
	<p style="color: green"><b>Bio:</b></p>	
Parul is a Data Science Evangelist here at H2O.ai. She combines Data Science , evangelism and community in her work. Her emphasis is to spread the information about H2O and Driverless AI to as many people as possible, She is also an active writer and has contributed towards various national and international publications.</p>

<br>
<br>

<div style="float: right;">
<%= image_tag("company/1.png")%>
</div>
<br>
<br>
<div>
	 <div style="float: right; padding-right: 30px">
<p><font size="+2" color="black"><b>Shivam Bansal</b></font><br>
Data Scientist at H2O.ai<br>

Singapore</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div style="float: right;padding-right: 200px">
	<font size="+1" color="black">follow on:</font><br>
<a href="https://twitter.com/shivamshaz" style="background: none"><i class="fa fa-twitter fa-3x" aria-hidden="true"></i></a>&nbsp;
<a href="https://www.linkedin.com/in/shivambansal1/" style="background: none"><i class="fa fa-linkedin fa-3x" aria-hidden="true"></i></a>&nbsp;
<a href="https://github.com/shivam5992" style="background: none"><i class="fa fa-github fa-3x" aria-hidden="true"></i></a>&nbsp;
<br>
<a href="http://www.shivambansal.com/" style="background: none;text-decoration: none"><font color="indigo">www.shivambansal.com</font></a>
<br>
<a href="https://www.kaggle.com/shivamb" style="background: none;text-decoration: none"><font color="brown"> www.kaggle.com</font></a>
</div>
<br><br>


</p>
<br>
<br>
<div >
<p style="color: green"><b>Bio:</b></p>	
	Masters from National University of Singapore - Business Analytics and Data Science,
	Full Stack Data Scientist with background in Computer Science,<br>
	Worked in Healthcare, Insurance, Retail, and Social Media domains

<br><br>
</div>
</div>
</div>

<br>
<br>
 
</body>
</html>

app/views/static_page/venue.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<style>
		body{
			background-color:  black;
			padding-top: 30px;
			padding-left: 30px;
			

		}
		.glow {
  font-size: 40px;
  color: #fff;
  text-align: center;
  -webkit-animation: glow 1s ease-in-out infinite alternate;
  -moz-animation: glow 1s ease-in-out infinite alternate;
  animation: glow 1s ease-in-out infinite alternate;
}

@-webkit-keyframes glow {
  from {
    text-shadow: 0 0 10px #fff, 0 0 20px #fff, 0 0 30px #e60073, 0 0 40px #e60073, 0 0 50px #e60073, 0 0 60px #e60073, 0 0 70px #e60073;
  }
  
  to {
    text-shadow: 0 0 20px #fff, 0 0 30px #ff4da6, 0 0 40px #ff4da6, 0 0 50px #ff4da6, 0 0 60px #ff4da6, 0 0 70px #ff4da6, 0 0 80px #ff4da6;
  }
}
.p{
	color: white;
	padding-left: 50px;
	font-size: 20px;
}
.d{
	
	color: white;
	font-size: 15px;
	font-style: italic;
}
a:link {
  color: yellow;
  background-color: transparent;
  text-decoration: none;
}
a:visited {
  color: yellow;
  background-color: transparent;
  text-decoration: none;
}
a:hover {
  color: yellow;
  background-color: transparent;
  text-decoration: underline;
}
a:active {
  color: yellow;
  background-color: transparent;
  text-decoration: underline;
}

	</style>


</head>
<body>
	<pre>

<h1 class="glow">
Your AI Transformation Part 2: 
Real World Use Cases
</h1>


            <div>
			<p class="p">Date:     Thursday, July 16, 2020</p>
			<p class="p">Time:     11:00 AM to 12:00 PM GMT+5:30</p>
			<p class="p">place:    online event</p>


			              

 <center><button type="button" class="btn btn-danger"><p class="d">Not yet registered? </p><%= link_to "Register Now", new_user_registration_path,background:"none" %><a href="/"></a></button></center>
            </div>








</pre>
	</body>
</html>